using LogKeeper.LogProducer.Logging;
using Serilog;
using Serilog.Events;

const string appName = "LogKeeper.LogProducer";
const string endpoint = "https://localhost:7222/logs";

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Information()
    .Enrich.WithProperty("CorrelationId", Guid.CreateVersion7().ToString())
    .Enrich.WithProperty("ClientIp", "127.0.0.1")
    .WriteTo.Console()
    .WriteTo.LogKeeperHttp(endpoint, appName, LogEventLevel.Information)
    .CreateLogger();

try
{
    TriggerLogs();
}
finally
{
    Log.CloseAndFlush();
}

static void TriggerLogs()
{
    Log.Information("Start log producer demo");

    for (var i = 1; i <= 3; i++)
    {
        Log.Information("Info log #{Index} generated at {GeneratedAtUtc}", i, DateTime.UtcNow);
    }

    Log.Warning("This is a warning from producer at {GeneratedAtUtc}", DateTime.UtcNow);

    try
    {
        throw new InvalidOperationException("Example exception from producer.");
    }
    catch (Exception ex)
    {
        Log.Error(ex, "Error log generated by TriggerLogs");
    }

    Log.Information("End log producer demo");
}
